name          'mpeter-jbossfuse'
version       '0.1.0'
source        'http://github.com/mpeter/mpeter-jbossfuse'
author        'Matt Peter'
license       'Apache 2.0'
summary       'JBoss Fuse Puppet Module'
description   ''
project_page  'https://github.com/mpeter/mpeter-jbossfuse'

dependency 'puppetlabs/stdlib'
